
cov_likelihood:
    num_samples: 5000
    condition_mask_fn: likelihood
    batch_size: 500
    num_bins: 50
    sample_kwargs: {"num_steps": 200, "sampling_method": "sde"}
    log_prob_kwargs: {"num_steps": 200}
